export const userPingUrl = 'http://localhost:8080/api/v1/manager/me'
export const managerAuthUrl = 'http://localhost:8080/api/v1/manager/auth'
export const notesFilterUrl = 'http://localhost:8080/api/v1/notes/filter'
export const notesAddUrl = 'http://localhost:8080/api/v1/notes/add'
export const notesRecentUrl = 'http://localhost:8080/api/v1/notes/recent'